checkerboard/widgets/urls.py
from django.conf.urls.defaults import *

urlpatterns = patterns('checkerboard.widgets.views',
    url(r'^$', 'index', name='widgets_index'),
    url(r'^upload/file/$', 'upload_file', name='widgets_upload_file'),
    url(r'^upload/blog_post/$', 'upload_blog_post', name='widgets_upload_blog_post'),
    url(r'^badges/$', 'badges', name='widgets_badges'),
    url(r'^badge_summary/$', 'badge_summary', name='widgets_badge_summary'),
    url(r'^login/$', 'login', name='widgets_login'),
    url(r'^logout/$', 'logout', name='widgets_logout'),
    url(r'^return/$', '_return', name='widgets_return'),
    url(r'^photos/$', 'photos', name='widgets_photos'),
    url(r'^photo/(?P<id>[0-9]+)$', 'photo', name='widgets_photo'),
    url(r'^public/$', 'public_frame', name='widgets_public_frame'),
    url(r'^widget/$', 'widget', name='widgets_widget'),
    url(r'^map/$', 'map', name='widgets_map'),
    url(r'^safari_no_cookie/$', 'safari_no_cookie', name='widgets_safari_no_cookie'),
)

checkerboard/widgets/forms.py
'''
Created on Mar 23, 2010

@author: edwards
'''
from django import forms
from django.forms.widgets import Textarea

class UploadPhotoForm(forms.Form):
    lat = forms.FloatField()
    lon = forms.FloatField()
    title = forms.CharField(max_length=50)
    tags = forms.CharField(max_length=50,required=False)
    photo  = forms.FileField()

class UploadBlogPostForm(forms.Form):
    title = forms.CharField(max_length=50)
    body = forms.CharField(widget=Textarea)
    tags = forms.CharField(max_length=50,required=False)

checkerboard/widgets/templates/widgets/badge_summary.html
<html>
  <head>
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/frame.css" type="text/css" media="screen">    
  </head>
  <body>
    <div class="header"><h3>Badges</h3></div>
    <div class="content">
      {% for badge in badges %}
        <div>
          <h4>{{ badge.title }}</h4>
          <img src="{{ badge.image.thumbnail.url }}" width="48" height="48" title="{{ badge.title }}" align="left"/>
          {{ badge.description }}
        </div>
      {% endfor %}
      <!-- referer: {{ referer }} -->
      <!-- initial referer: {{ initial_referer }} -->
      <!-- user: {{ username }} -->
    </div>
  </body>
</html>

checkerboard/widgets/templates/widgets/badges.html
<html>
  <head>
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/frame.css" type="text/css" media="screen">    
  </head>
  <body>
    <div class="header"><h3>{% spaceless %}
      {% if username %}
        {{ username }}'s
      {% else %}
        My
      {% endif %} Badges{% endspaceless %}</h3></div>
    <div class="content">
      {% if username %}
          {% for win in wins %}
            <a href="http://example.com/pages/spotter/badges/" target="_parent"><img src="{{ win.badge.image.thumbnail.url }}" width="48" height="48" title="{{ win.badge.title }}"/></a>
          {% endfor %}
      {% else %}
        {% if request.user %}
          {% if wins %}
            {% for win in wins %}
              <img src="{{ win.badge.image.thumbnail.url }}" width="48" height="48" title="{{ win.badge.title }}"/>
            {% endfor %}
          {% else %}
            Start earning badges now!
          {% endif %}
        {% endif %}
      {% endif %}
    </div>
  </body>
</html>

checkerboard/widgets/templates/widgets/blog_post.html
{{ response }}

checkerboard/widgets/templates/widgets/frame.html
<html>
	<head>
		<link rel="stylesheet" href="{{ MEDIA_URL }}css/frame.css" type="text/css" media="screen">    
		<script src="http://maps.google.com/maps?file=api&amp;v=2&amp;sensor=true&amp;key=ABQIAAAACvkIm8uaU_cRqC5X2qgbvBTHZvGzQVZ4ybsi3UEDQmtKj24ByxT0uFskSC6G4vzLU-hVxRl1YjAAXg" type="text/javascript"></script>
		<script>
		    var map;
		    var recordGeoXml;
		    var toggleState = 1;
		
		    function initialize() {
		      if (GBrowserIsCompatible()) {
		        recordGeoXml = new GGeoXml("http://example.com/records.kml");
		        map = new GMap2(document.getElementById("map_canvas")); 
		        map.setCenter(new GLatLng(40.74633,-73.84633), 15); 
		        map.setUIToDefault();
		      }
		    } 
		
		    function toggleMyKml() {
		      if (toggleState == 1) {
		        map.addOverlay(recordGeoXml);
		        toggleState = 0;
		      } else {
		        map.removeOverlay(recordGeoXml);
		        toggleState = 1;
		      }
		    }
		
		</script>
	</head>
    <body onload="initialize()" onunload="GUnload()">
        <div class="header"><h3>Welcome to the Spotter Group!</h3></div>
        <div id="map_canvas" style="width: 600px; height: 400px"></div>
        <input type="button" value="Swap Layers" onClick="toggleMyKml();"/>
        <div class="content">
            <div>Take a look at what everyone has been up to!  Check out the <a href="http://example.com/pages/spotter/lab" target="_parent">spotter Lab</a>!</div>
            <div>Here is a list of recent badge recipients.  Learn <a href="http://example.com/pages/spotter/badges" target="_parent">more about badges</a>!</div>
            <div>
                <ul>
                {% for win in wins %}
                 {% if win.user.first_name %}
                   <li><strong>spotter {{win.badge.title}} Badge</strong> earned by <em>{{win.user.first_name}} {{win.user.last_name}}</em> {{win.created|timesince}} ago</li>
                 {% else %}
                   <li><strong>spotter {{win.badge.title}} Badge</strong> earned by <em>{{win.user.username}}</em> {{win.created|timesince}} ago</li>
                 {% endif %}
                {% endfor %}
                </ul>
            </div>
        </div>
    </body>
</html>

checkerboard/widgets/templates/widgets/index.html
{% extends 'base.html' %}
{% block content %}
<iframe src="{% url widgets_widget %}" width="800" height="600"></iframe>
{% endblock %}

checkerboard/widgets/templates/widgets/map.html
{% load dajaxice_templatetags %}
<html>
  <head>
    <link rel="stylesheet" href="/media/css/blueprint/screen.css" type="text/css" media="screen, projection">
    <link rel="stylesheet" href="/media/css/blueprint/print.css" type="text/css" media="print">    
    <!--[if lt IE 8]><link rel="stylesheet" href="/media/css/blueprint/ie.css" type="text/css" media="screen, projection"><![endif]-->
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/frame.css" type="text/css" media="screen">
    <link rel="stylesheet" href="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/themes/south-street/jquery-ui.css" type="text/css" media="screen">
    <style>
      #map {
        width: 600px;
        height: 320px;
      }
      #tl {
        width: 600px;
        height: 320px;
      }
      #logout-link, #logout-link:active, #logout-link:hover, #logout-link:visited  {
        color: #fff;
        font-size: 50%;
      }
    </style>    
    <style type="text/css">
      body { font-size: 62.5%; font-family: Verdana;}
      label, input { display:block; }
      input.text { margin-bottom:12px; padding: .4em; }
      fieldset { padding:0; border:0; margin-top:25px; }
      .ui-dialog .ui-state-error { padding: .3em; }
      .validateTips { border: 1px solid transparent; padding: 0.3em; }
      .timeline-event-label { background-color: #fff; padding: 2px; opacity: .5}    
    </style>
    <script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js" type="text/javascript"></script>
    <script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js" type="text/javascript"></script>
    {% dajaxice_js_import %}
    <script src="{{ MEDIA_URL }}js/jquery.dajax.core.js" type="text/javascript" charset="utf-8"></script>
    <script src="{{ MEDIA_URL }}js/thickbox-compressed.js" type="text/javascript" charset="utf-8"></script>
    <script type="text/javascript" src="http://maps.google.com/maps/api/js?sensor=false"></script>
    <script src="{{ MEDIA_URL }}js/timeline_js/timeline-api.js?bundle=true" type="text/javascript"></script>
    <script src="{{ MEDIA_URL }}js/map.js" type="text/javascript"></script>
  </head>
  <body onload="initialize('{{ MEDIA_URL }}')">
    <div class="header"><h3>{{request.user.username}}'s Spotter Laboratory <a href="{% url widgets_logout %}?next={% url widgets_map %}" id="logout-link">[logout]</a></h3></div>
    <div id="readDialog" class="container">
      <div id="readDialogHeader" class="span-12 last">
        <div id="readDialogAuthor" class="span-7"></div>
        <div id="readDialogSince" class="span-5 last"></div>
      </div>
      <div id="readDialogContent" class="span-12 last">
        <div id="readDialogImage" class="span-7">
          <img src="{{ MEDIA_URL }}img/spotter/missing_spotting.png" width="240" height="320"/>
          <span id="readDialogCaption"></span>
        </div>
        <div id="readDialogAnswers" class="span-5 last">
          <dl>
          </dl>
        </div>
      </div>
    </div>
    <div id="formDialog">
      <div id="formDialogHeader" class="span-12 last">
        To add this observation to the remote app, fill in the following:
      </div>
      <div id="formDialogContent" class="span-12 last">
        <form>
          <fieldset>
            <label for="formDialogTitle">Title:</label>
            <input type="text" id="formDialogTitle" size="50" name="title" value=""/>
            <div id="formDialogImageBody" name="image_body" style="display:none;"></div>
            <label for="formDialogBody">Blog Post:</label>
            <textarea id="formDialogBody" name="body"></textarea>
            <label for="formDialogTags">Tags (comma separated):</label>
            <input type="text" id="formDialogTags" size="50" name="tags"/>
          </fieldset>
        </form> 
      </div>
    </div>
    <div id="confirmDialog">
      <div id="confirmDialogHeader" class="span-12 last">
        Thanks for adding this observation to the remote app! You can 
        <a href="{{remote_app_server}}blog_posts/" target="_parent" id="confirmDialogViewPost">view your post</a> and edit it some more!
      </div>
    </div>
    <div id="map"></div>
    <div id="commonFilters">
      Filter by
      scientist: 
      <select id="userSelect">
        <option value="">--All--</option>
        {% for user in users %}
          <option value="{{ user.username }}">{{ user.username }}</option>
        {% endfor %}
      </select>
      station: 
      <select id="stationSelect">
        <option value="">--All--</option>
        {% for station in stations %}
          <option value="{{ station.id }}">{{ station.title }}</option>
        {% endfor %}
      </select>
      activity: 
      <select id="inquirySelect">
        <option value="">--All--</option>
      </select>
    </div>
    <div id="messageDisplay"></div>
    <div id="tl" class="timeline-default"></div>
    <div class="controls" id="controls"></div>
    <!-- referer: {{ referer }} -->
    <!-- initial referer: {{ initial_referer }} -->    
    <script>
    </script>
  </body>
</html>

checkerboard/widgets/templates/widgets/photo.html
{% extends 'base.html' %}
{% block content %}
<div>
<img src="http://example.com/{{ photo.image_paths.show }}"/>
</div>
<div>
<img src="http://maps.google.com/maps/api/staticmap?center={{ record.geometry.coordinates.1 }},{{ record.geometry.coordinates.0 }}&zoom=14&size=400x400&sensor=false&markers=color:blue|label:P|{{ record.geometry.coordinates.1 }},{{ record.geometry.coordinates.0 }}" width="400" height="400"/>
</div>

{% endblock %}

checkerboard/widgets/templates/widgets/photos.html
{% extends 'base.html' %}
{% block content %}
Photos (JSON) : {{ photos_json }}
{% endblock %}

checkerboard/widgets/templates/widgets/return.html
{% extends 'base.html' %}
{% block content %}
This is the return page.
Message {{ message }}


{% if request.session.initial_referer %}
  The initial referer was {{request.session.initial_referer}}
{% endif %}
{% endblock %}

checkerboard/widgets/templates/widgets/upload.html
{% extends 'base.html' %}
{% block header %}
<script type="text/javascript"> 
function findLocation() {   
  if(navigator.geolocation) {     
    navigator.geolocation.getCurrentPosition(successCallback,errorCallback);   
  } else {     
    // Do something to alert the user   
  } 
} 

function successCallback(position) {
  var lat = position.coords.latitude;
  var lon = position.coords.longitude;   
  $("input#id_lat").val("" + lat);
  $("input#id_lon").val("" + lon);  
} 

function errorCallback() {
  // Do something with the error 
} 

$(document).ready(function() {
    findLocation();
});



</script>
{% endblock %}
{% block content %}
{{ response }}
{{ error.read }}
<form enctype="multipart/form-data" method="post">
{{ form }}
<input type="submit"/>

</form>
{% endblock %}

checkerboard/widgets/templates/widgets/widget.html
<html>
  <head>
    <link rel="stylesheet" href="{{ MEDIA_URL }}css/frame.css" type="text/css" media="screen"> 
    <script src="{{ MEDIA_URL }}js/timeline_js/timeline-api.js?bundle=true" type="text/javascript">
    </script>
  </head>

{% ifequal group_id "544" %}
  <body onload="initialize()" onunload="GUnload()">
    <div id="map_canvas" style="width: 600px; height: 400px"></div>
    <input type="button" value="Swap Layers" onClick="toggleMyKml();"/>
  </body>

{% else %}    

  {% ifequal group_id "548" %}
    <body>
      <div class="header"><h3>Welcome to the City of Neighborhoods Group!</h3></div>
       <div class="content">
        <div>Lot of exciting things are happening soon.  Keep an eye on this area for more updates!</div>
      </div>
      <!-- referer: {{ referer }} -->
      <!-- initial referer: {{ initial_referer }} -->
    </body>
  
  {% else %}
    {% ifequal group_id "549" %}
      <body onload="onLoad();">
        <div class="header"><h3>Welcome to the spotter Group!</h3></div>
         <div class="content">
          <div>Lot of exciting things are happening soon.  Keep an eye on this area for more updates!</div>
        </div>
        <!-- referer: {{ referer }} -->
        <!-- initial referer: {{ initial_referer }} -->
      </body>
    {% else %}  
      <body>
        <div class="header"><h3>Welcome to the your NYCLN Group!</h3></div>
         <div class="content">
          <div>Lot of exciting things are happening soon.  Keep an eye on this area for more updates!</div>
         </div>
        <!-- referer: {{ referer }} -->
        <!-- initial referer: {{ initial_referer }} -->
      </body>
    {% endifequal %}
  {% endifequal %}
  
  {% if request.session.initial_referer %}
  {% endif %}

{% endifequal %}
</html>